server:
  port: 9093

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro_services
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    open-in-view: true
    show-sql: true
  application:
    name: Hotel-Service

eureka:
  instance:
    prefer-ip-address: true 
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZonce: http://localhost:8761/eureka      